### ISSUE TITLE
requirements.txt에서 dependency 문제

### ISSUE THREAD

**Issue by domik017123** [traumasj201/AdapTex#1]
torch 2.1.0이랑 torchdata가 안맞아서 torch==2.0.1로 바꿨는데 해당 에러가 뜹니다.
The conflict is caused by:
    The user requested torch==2.0.1
    entmax 1.1 depends on torch>=1.0
    timm 0.5.4 depends on torch>=1.4
    torchdata 0.6.1 depends on torch==2.0.1
    torchtext 0.15.2 depends on torch==2.0.1
    torchvision 0.16.0 depends on torch==2.1.0

**Comment by traumasj201** [comment]
좋은 이슈 감사합니다! 
수정 완료 했습니다.
